version: "3"

services:
  app:
    build: .
    volumes:
      - ./app/:/src/
    ports:
      - 3000:3000
    depends_on:
      - mongodb
    links:
      - mongodb

  mongodb:
    image: mongo:3
    ports:
      - 27017:27017
