version: "3"

services:
  app:
    build: .
    volumes:
      - ./app/:/src/
      - /src/node_modules
    ports:
      - 3000:3000
    depends_on:
      - mongo
    links:
      - mongo

  mongo:
    image: mongo:3
    ports:
      - 27017:27017
